/**
 * GENERATED by scripts/build-dist.ts — do not hand-edit.
 *
 * A static import() map. Rolldown/Vite cannot code-split a dynamic
 * template-literal specifier resolving into node_modules
 * (`import(\`@pb/templates/dist/${id}\`)` fails to build), so this file is
 * regenerated from the template registry every time `bun run build` runs.
 *
 * Import this ONLY from the web app's preview iframe entry (src/preview.tsx).
 * If the builder UI ever imports it, template code stops being isolated
 * from the main bundle — see the templates repo README for the CI check
 * that guards this.
 */
import type { ComponentType } from "react";
import type { PortfolioData } from "./schema.js";

export type TemplateComponent = ComponentType<{ data: PortfolioData }>;

export const TEMPLATE_LOADERS: Record<string, () => Promise<{ default: TemplateComponent }>> = {
	aurora: () => import("@pb/templates/dist/aurora/index.js"),
	monolith: () => import("@pb/templates/dist/monolith/index.js"),
	prism: () => import("@pb/templates/dist/prism/index.js"),
};
